# Generated by Django 5.0.7 on 2024-07-14 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_rename_craeted_date_chat_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='message',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
