# Generated by Django 5.0.7 on 2024-07-14 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_rename_message_chat_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='messages',
            field=models.JSONField(default={}),
        ),
    ]
