# Generated by Django 5.0.7 on 2024-08-04 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SymptomReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=200)),
                ('core_symptoms', models.TextField()),
                ('duration_weeks', models.IntegerField()),
                ('severity', models.CharField(choices=[('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe')], max_length=50)),
                ('location', models.CharField(max_length=200)),
                ('associated_symptoms', models.CharField(blank=True, max_length=500)),
                ('medical_history', models.CharField(blank=True, max_length=500)),
                ('lifestyle_factors', models.CharField(blank=True, max_length=500)),
                ('recent_exposures', models.CharField(blank=True, max_length=500)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
