# Generated by Django 5.0.7 on 2024-08-04 15:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptom_checker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='symptomreport',
            name='ai_response',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='symptomreport',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='symptomreport',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
